// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: BodyJacobian
 *
 * Args:
 *     joint_angles: Matrix71
 *
 * Outputs:
 *     res: Matrix67
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 7> Luppersensorbodyjacobian(
    const Eigen::Matrix<Scalar, 7, 1>& joint_angles) {
  // Total ops: 268

  // Input arrays

  // Intermediate terms (59)
  const Scalar _tmp0 = 1 - std::cos(joint_angles(0, 0));
  const Scalar _tmp1 = Scalar(0.36863892073799998) * _tmp0;
  const Scalar _tmp2 = std::sin(joint_angles(0, 0));
  const Scalar _tmp3 = Scalar(0.47771400000000003) * _tmp2;
  const Scalar _tmp4 = _tmp1 + _tmp3;
  const Scalar _tmp5 = 1 - std::cos(joint_angles(1, 0));
  const Scalar _tmp6 = 1 - Scalar(0.64784630232100004) * _tmp5;
  const Scalar _tmp7 = 1 - Scalar(0.728210975245) * _tmp0;
  const Scalar _tmp8 = Scalar(0.47764205971399998) * _tmp5;
  const Scalar _tmp9 = std::sin(joint_angles(1, 0));
  const Scalar _tmp10 = Scalar(0.249048550476) * _tmp0;
  const Scalar _tmp11 = Scalar(0.70710700000000004) * _tmp2;
  const Scalar _tmp12 = _tmp10 - _tmp11;
  const Scalar _tmp13 = _tmp12 * _tmp9;
  const Scalar _tmp14 = Scalar(0.80488899999999997) * _tmp13 + _tmp4 * _tmp6 - _tmp7 * _tmp8;
  const Scalar _tmp15 = std::sin(joint_angles(2, 0));
  const Scalar _tmp16 = std::cos(joint_angles(2, 0));
  const Scalar _tmp17 = 1 - Scalar(0.35215441747600001) * _tmp5;
  const Scalar _tmp18 = Scalar(0.59342600000000001) * _tmp13 + _tmp17 * _tmp7 - _tmp4 * _tmp8;
  const Scalar _tmp19 = _tmp14 * _tmp15 + _tmp16 * _tmp18;
  const Scalar _tmp20 = Scalar(0.80488899999999997) * _tmp9;
  const Scalar _tmp21 = Scalar(0.59342600000000001) * _tmp9;
  const Scalar _tmp22 = 1 - Scalar(1.000000719797) * _tmp5;
  const Scalar _tmp23 = _tmp12 * _tmp22 - _tmp20 * _tmp4 - _tmp21 * _tmp7;
  const Scalar _tmp24 = _tmp14 * _tmp16 - _tmp15 * _tmp18;
  const Scalar _tmp25 = -Scalar(0.01115) * _tmp19 - Scalar(0.20200000000000001) * _tmp23 -
                        Scalar(0.046719999999999998) * _tmp24;
  const Scalar _tmp26 = 1 - Scalar(0.499999805352) * _tmp0;
  const Scalar _tmp27 = Scalar(0.337794913398) * _tmp0;
  const Scalar _tmp28 = Scalar(0.52133399999999996) * _tmp2;
  const Scalar _tmp29 = _tmp27 + _tmp28;
  const Scalar _tmp30 = _tmp1 - _tmp3;
  const Scalar _tmp31 = _tmp20 * _tmp29 + _tmp26 * _tmp6 - _tmp30 * _tmp8;
  const Scalar _tmp32 = _tmp17 * _tmp30 + _tmp21 * _tmp29 - _tmp26 * _tmp8;
  const Scalar _tmp33 = -_tmp15 * _tmp32 + _tmp16 * _tmp31;
  const Scalar _tmp34 = -_tmp20 * _tmp26 - _tmp21 * _tmp30 + _tmp22 * _tmp29;
  const Scalar _tmp35 = _tmp15 * _tmp31 + _tmp16 * _tmp32;
  const Scalar _tmp36 = -Scalar(0.046719999999999998) * _tmp33 -
                        Scalar(0.20200000000000001) * _tmp34 - Scalar(0.01115) * _tmp35;
  const Scalar _tmp37 = _tmp27 - _tmp28;
  const Scalar _tmp38 = 1 - Scalar(0.77178944900500002) * _tmp0;
  const Scalar _tmp39 = _tmp10 + _tmp11;
  const Scalar _tmp40 = _tmp20 * _tmp38 + _tmp37 * _tmp6 - _tmp39 * _tmp8;
  const Scalar _tmp41 = _tmp17 * _tmp39 + _tmp21 * _tmp38 - _tmp37 * _tmp8;
  const Scalar _tmp42 = -_tmp15 * _tmp41 + _tmp16 * _tmp40;
  const Scalar _tmp43 = _tmp15 * _tmp40 + _tmp16 * _tmp41;
  const Scalar _tmp44 = -_tmp20 * _tmp37 - _tmp21 * _tmp39 + _tmp22 * _tmp38;
  const Scalar _tmp45 = -Scalar(0.046719999999999998) * _tmp42 - Scalar(0.01115) * _tmp43 -
                        Scalar(0.20200000000000001) * _tmp44;
  const Scalar _tmp46 = _tmp15 * _tmp20 + _tmp16 * _tmp21;
  const Scalar _tmp47 = -_tmp15 * _tmp21 + _tmp16 * _tmp20;
  const Scalar _tmp48 = -Scalar(0.20200000000000001) * _tmp22 - Scalar(0.01115) * _tmp46 -
                        Scalar(0.046719999999999998) * _tmp47;
  const Scalar _tmp49 = -_tmp16 * _tmp8;
  const Scalar _tmp50 = -_tmp15 * _tmp17 + _tmp49;
  const Scalar _tmp51 = _tmp15 * _tmp8;
  const Scalar _tmp52 = _tmp16 * _tmp17 - _tmp51;
  const Scalar _tmp53 = -Scalar(0.046719999999999998) * _tmp50 - Scalar(0.01115) * _tmp52 +
                        Scalar(0.11987205200000001) * _tmp9;
  const Scalar _tmp54 = _tmp16 * _tmp6 + _tmp51;
  const Scalar _tmp55 = _tmp15 * _tmp6 + _tmp49;
  const Scalar _tmp56 = -Scalar(0.046719999999999998) * _tmp54 - Scalar(0.01115) * _tmp55 +
                        Scalar(0.16258757800000001) * _tmp9;
  const Scalar _tmp57 = -Scalar(0.01115) * _tmp15 - Scalar(0.046719999999999998) * _tmp16;
  const Scalar _tmp58 = Scalar(0.046719999999999998) * _tmp15 - Scalar(0.01115) * _tmp16;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 7> _res;

  _res.setZero();

  _res(0, 0) = Scalar(0.47771400000000003) * _tmp24 * _tmp36 -
               Scalar(0.70710700000000004) * _tmp24 * _tmp45 -
               Scalar(0.47771400000000003) * _tmp25 * _tmp33 +
               Scalar(0.70710700000000004) * _tmp25 * _tmp42 +
               Scalar(0.52133399999999996) * _tmp33 * _tmp45 -
               Scalar(0.52133399999999996) * _tmp36 * _tmp42;
  _res(1, 0) = Scalar(0.47771400000000003) * _tmp19 * _tmp36 -
               Scalar(0.70710700000000004) * _tmp19 * _tmp45 -
               Scalar(0.47771400000000003) * _tmp25 * _tmp35 +
               Scalar(0.70710700000000004) * _tmp25 * _tmp43 +
               Scalar(0.52133399999999996) * _tmp35 * _tmp45 -
               Scalar(0.52133399999999996) * _tmp36 * _tmp43;
  _res(2, 0) = Scalar(0.47771400000000003) * _tmp23 * _tmp36 -
               Scalar(0.70710700000000004) * _tmp23 * _tmp45 -
               Scalar(0.47771400000000003) * _tmp25 * _tmp34 +
               Scalar(0.70710700000000004) * _tmp25 * _tmp44 +
               Scalar(0.52133399999999996) * _tmp34 * _tmp45 -
               Scalar(0.52133399999999996) * _tmp36 * _tmp44;
  _res(3, 0) = Scalar(0.52133399999999996) * _tmp24 + Scalar(0.70710700000000004) * _tmp33 +
               Scalar(0.47771400000000003) * _tmp42;
  _res(4, 0) = Scalar(0.52133399999999996) * _tmp19 + Scalar(0.70710700000000004) * _tmp35 +
               Scalar(0.47771400000000003) * _tmp43;
  _res(5, 0) = Scalar(0.52133399999999996) * _tmp23 + Scalar(0.70710700000000004) * _tmp34 +
               Scalar(0.47771400000000003) * _tmp44;
  _res(0, 1) = Scalar(0.59342600000000001) * _tmp47 * _tmp53 +
               Scalar(0.80488899999999997) * _tmp47 * _tmp56 -
               Scalar(0.59342600000000001) * _tmp48 * _tmp50 -
               Scalar(0.80488899999999997) * _tmp48 * _tmp54;
  _res(1, 1) = Scalar(0.59342600000000001) * _tmp46 * _tmp53 +
               Scalar(0.80488899999999997) * _tmp46 * _tmp56 -
               Scalar(0.59342600000000001) * _tmp48 * _tmp52 -
               Scalar(0.80488899999999997) * _tmp48 * _tmp55;
  _res(2, 1) = Scalar(0.80488899999999997) * _tmp20 * _tmp48 +
               Scalar(0.59342600000000001) * _tmp21 * _tmp48 +
               Scalar(0.59342600000000001) * _tmp22 * _tmp53 +
               Scalar(0.80488899999999997) * _tmp22 * _tmp56;
  _res(3, 1) = -Scalar(0.80488899999999997) * _tmp50 + Scalar(0.59342600000000001) * _tmp54;
  _res(4, 1) = -Scalar(0.80488899999999997) * _tmp52 + Scalar(0.59342600000000001) * _tmp55;
  _res(0, 2) = _tmp15 * _tmp57 + _tmp16 * _tmp58;
  _res(1, 2) = _tmp15 * _tmp58 - _tmp16 * _tmp57;
  _res(5, 2) = -1;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
