// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: BodyJacobian
 *
 * Args:
 *     joint_angles: Matrix71
 *
 * Outputs:
 *     res: Matrix67
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 7> Rwristsensorbodyjacobian(
    const Eigen::Matrix<Scalar, 7, 1>& joint_angles) {
  // Total ops: 736

  // Input arrays

  // Intermediate terms (194)
  const Scalar _tmp0 = std::cos(joint_angles(3, 0));
  const Scalar _tmp1 = 1 - std::cos(joint_angles(0, 0));
  const Scalar _tmp2 = Scalar(0.337794913398) * _tmp1;
  const Scalar _tmp3 = std::sin(joint_angles(0, 0));
  const Scalar _tmp4 = Scalar(0.52133399999999996) * _tmp3;
  const Scalar _tmp5 = _tmp2 - _tmp4;
  const Scalar _tmp6 = 1 - std::cos(joint_angles(1, 0));
  const Scalar _tmp7 = 1 - Scalar(0.64784630232100004) * _tmp6;
  const Scalar _tmp8 = 1 - Scalar(0.77178944900500002) * _tmp1;
  const Scalar _tmp9 = std::sin(joint_angles(1, 0));
  const Scalar _tmp10 = Scalar(0.80488899999999997) * _tmp9;
  const Scalar _tmp11 = Scalar(0.249048550476) * _tmp1;
  const Scalar _tmp12 = Scalar(0.70710700000000004) * _tmp3;
  const Scalar _tmp13 = _tmp11 + _tmp12;
  const Scalar _tmp14 = Scalar(0.47764205971399998) * _tmp6;
  const Scalar _tmp15 = _tmp10 * _tmp8 - _tmp13 * _tmp14 + _tmp5 * _tmp7;
  const Scalar _tmp16 = std::sin(joint_angles(2, 0));
  const Scalar _tmp17 = std::cos(joint_angles(2, 0));
  const Scalar _tmp18 = 1 - Scalar(0.35215441747600001) * _tmp6;
  const Scalar _tmp19 = Scalar(0.59342600000000001) * _tmp9;
  const Scalar _tmp20 = _tmp13 * _tmp18 - _tmp14 * _tmp5 + _tmp19 * _tmp8;
  const Scalar _tmp21 = _tmp15 * _tmp16 + _tmp17 * _tmp20;
  const Scalar _tmp22 = std::sin(joint_angles(3, 0));
  const Scalar _tmp23 = 1 - Scalar(1.000000719797) * _tmp6;
  const Scalar _tmp24 = -_tmp10 * _tmp5 - _tmp13 * _tmp19 + _tmp23 * _tmp8;
  const Scalar _tmp25 = _tmp0 * _tmp21 + _tmp22 * _tmp24;
  const Scalar _tmp26 = std::sin(joint_angles(4, 0));
  const Scalar _tmp27 = _tmp15 * _tmp17 - _tmp16 * _tmp20;
  const Scalar _tmp28 = std::cos(joint_angles(4, 0));
  const Scalar _tmp29 = -_tmp25 * _tmp26 + _tmp27 * _tmp28;
  const Scalar _tmp30 = std::cos(joint_angles(5, 0));
  const Scalar _tmp31 = _tmp0 * _tmp24 - _tmp21 * _tmp22;
  const Scalar _tmp32 = std::sin(joint_angles(5, 0));
  const Scalar _tmp33 = _tmp29 * _tmp30 - _tmp31 * _tmp32;
  const Scalar _tmp34 = 1 - Scalar(0.499999805352) * _tmp1;
  const Scalar _tmp35 = Scalar(0.36863892073799998) * _tmp1;
  const Scalar _tmp36 = Scalar(0.47771400000000003) * _tmp3;
  const Scalar _tmp37 = _tmp35 - _tmp36;
  const Scalar _tmp38 = _tmp2 + _tmp4;
  const Scalar _tmp39 = -_tmp14 * _tmp34 + _tmp18 * _tmp37 + _tmp19 * _tmp38;
  const Scalar _tmp40 = _tmp10 * _tmp38 - _tmp14 * _tmp37 + _tmp34 * _tmp7;
  const Scalar _tmp41 = _tmp16 * _tmp40 + _tmp17 * _tmp39;
  const Scalar _tmp42 = -_tmp10 * _tmp34 - _tmp19 * _tmp37 + _tmp23 * _tmp38;
  const Scalar _tmp43 = _tmp0 * _tmp42 - _tmp22 * _tmp41;
  const Scalar _tmp44 = _tmp0 * _tmp41 + _tmp22 * _tmp42;
  const Scalar _tmp45 = -_tmp16 * _tmp39 + _tmp17 * _tmp40;
  const Scalar _tmp46 = -_tmp26 * _tmp44 + _tmp28 * _tmp45;
  const Scalar _tmp47 = _tmp30 * _tmp43 + _tmp32 * _tmp46;
  const Scalar _tmp48 = std::sin(joint_angles(6, 0));
  const Scalar _tmp49 = _tmp26 * _tmp45 + _tmp28 * _tmp44;
  const Scalar _tmp50 = std::cos(joint_angles(6, 0));
  const Scalar _tmp51 = _tmp47 * _tmp48 + _tmp49 * _tmp50;
  const Scalar _tmp52 = Scalar(0.58030000000000004) - Scalar(0.58030000000000004) * _tmp30;
  const Scalar _tmp53 = Scalar(0.30359999999999998) * _tmp22;
  const Scalar _tmp54 = 1 - _tmp0;
  const Scalar _tmp55 = Scalar(0.30359999999999998) * _tmp54;
  const Scalar _tmp56 = Scalar(0.58030000000000004) * _tmp32;
  const Scalar _tmp57 = 1 - _tmp50;
  const Scalar _tmp58 = Scalar(0.58030000000000004) * _tmp57;
  const Scalar _tmp59 = _tmp30 * _tmp46 - _tmp32 * _tmp43;
  const Scalar _tmp60 = _tmp48 * _tmp49;
  const Scalar _tmp61 = _tmp47 * _tmp50 - _tmp60;
  const Scalar _tmp62 = -_tmp41 * _tmp53 - _tmp42 * _tmp55 - _tmp43 * _tmp52 + _tmp46 * _tmp56 -
                        _tmp47 * _tmp58 + Scalar(0.023210000000000001) * _tmp51 +
                        Scalar(0.040910000000000002) * _tmp59 -
                        Scalar(0.58030000000000004) * _tmp60 - Scalar(0.63) * _tmp61;
  const Scalar _tmp63 = _tmp29 * _tmp32 + _tmp30 * _tmp31;
  const Scalar _tmp64 = _tmp25 * _tmp28 + _tmp26 * _tmp27;
  const Scalar _tmp65 = _tmp48 * _tmp63 + _tmp50 * _tmp64;
  const Scalar _tmp66 = _tmp48 * _tmp64;
  const Scalar _tmp67 = _tmp50 * _tmp63 - _tmp66;
  const Scalar _tmp68 = -_tmp21 * _tmp53 - _tmp24 * _tmp55 + _tmp29 * _tmp56 - _tmp31 * _tmp52 +
                        Scalar(0.040910000000000002) * _tmp33 - _tmp58 * _tmp63 +
                        Scalar(0.023210000000000001) * _tmp65 -
                        Scalar(0.58030000000000004) * _tmp66 - Scalar(0.63) * _tmp67;
  const Scalar _tmp69 = _tmp35 + _tmp36;
  const Scalar _tmp70 = 1 - Scalar(0.728210975245) * _tmp1;
  const Scalar _tmp71 = _tmp11 - _tmp12;
  const Scalar _tmp72 = _tmp10 * _tmp71 - _tmp14 * _tmp70 + _tmp69 * _tmp7;
  const Scalar _tmp73 = -_tmp14 * _tmp69 + _tmp18 * _tmp70 + _tmp19 * _tmp71;
  const Scalar _tmp74 = -_tmp16 * _tmp73 + _tmp17 * _tmp72;
  const Scalar _tmp75 = _tmp16 * _tmp72 + _tmp17 * _tmp73;
  const Scalar _tmp76 = -_tmp10 * _tmp69 - _tmp19 * _tmp70 + _tmp23 * _tmp71;
  const Scalar _tmp77 = _tmp0 * _tmp75 + _tmp22 * _tmp76;
  const Scalar _tmp78 = -_tmp26 * _tmp77 + _tmp28 * _tmp74;
  const Scalar _tmp79 = _tmp22 * _tmp75;
  const Scalar _tmp80 = _tmp0 * _tmp76 - _tmp79;
  const Scalar _tmp81 = _tmp30 * _tmp78 - _tmp32 * _tmp80;
  const Scalar _tmp82 = _tmp32 * _tmp78;
  const Scalar _tmp83 = _tmp26 * _tmp74 + _tmp28 * _tmp77;
  const Scalar _tmp84 = _tmp48 * _tmp83;
  const Scalar _tmp85 = _tmp30 * _tmp80 + _tmp82;
  const Scalar _tmp86 = _tmp50 * _tmp85 - _tmp84;
  const Scalar _tmp87 = _tmp48 * _tmp85 + _tmp50 * _tmp83;
  const Scalar _tmp88 =
      -_tmp52 * _tmp80 - _tmp55 * _tmp76 - _tmp58 * _tmp85 - Scalar(0.30359999999999998) * _tmp79 +
      Scalar(0.040910000000000002) * _tmp81 + Scalar(0.58030000000000004) * _tmp82 -
      Scalar(0.58030000000000004) * _tmp84 - Scalar(0.63) * _tmp86 +
      Scalar(0.023210000000000001) * _tmp87;
  const Scalar _tmp89 = -_tmp14 * _tmp17;
  const Scalar _tmp90 = _tmp16 * _tmp7 + _tmp89;
  const Scalar _tmp91 = _tmp22 * _tmp90;
  const Scalar _tmp92 = _tmp14 * _tmp16;
  const Scalar _tmp93 = _tmp17 * _tmp7 + _tmp92;
  const Scalar _tmp94 = _tmp0 * _tmp90 - _tmp10 * _tmp22;
  const Scalar _tmp95 = -_tmp26 * _tmp94 + _tmp28 * _tmp93;
  const Scalar _tmp96 = _tmp32 * _tmp95;
  const Scalar _tmp97 = -_tmp0 * _tmp10 - _tmp91;
  const Scalar _tmp98 = _tmp30 * _tmp95 - _tmp32 * _tmp97;
  const Scalar _tmp99 = _tmp26 * _tmp93 + _tmp28 * _tmp94;
  const Scalar _tmp100 = Scalar(0.58030000000000004) * _tmp48;
  const Scalar _tmp101 = _tmp30 * _tmp97 + _tmp96;
  const Scalar _tmp102 = _tmp101 * _tmp48 + _tmp50 * _tmp99;
  const Scalar _tmp103 = _tmp101 * _tmp50 - _tmp48 * _tmp99;
  const Scalar _tmp104 = _tmp54 * _tmp9;
  const Scalar _tmp105 =
      -_tmp100 * _tmp99 - _tmp101 * _tmp58 + Scalar(0.023210000000000001) * _tmp102 -
      Scalar(0.63) * _tmp103 + Scalar(0.24436430040000001) * _tmp104 - _tmp52 * _tmp97 -
      Scalar(0.30359999999999998) * _tmp91 + Scalar(0.58030000000000004) * _tmp96 +
      Scalar(0.040910000000000002) * _tmp98;
  const Scalar _tmp106 = _tmp10 * _tmp16 + _tmp17 * _tmp19;
  const Scalar _tmp107 = _tmp106 * _tmp22;
  const Scalar _tmp108 = _tmp0 * _tmp23 - _tmp107;
  const Scalar _tmp109 = _tmp0 * _tmp106 + _tmp22 * _tmp23;
  const Scalar _tmp110 = _tmp10 * _tmp17 - _tmp16 * _tmp19;
  const Scalar _tmp111 = -_tmp109 * _tmp26 + _tmp110 * _tmp28;
  const Scalar _tmp112 = -_tmp108 * _tmp32 + _tmp111 * _tmp30;
  const Scalar _tmp113 = _tmp111 * _tmp32;
  const Scalar _tmp114 = _tmp108 * _tmp30 + _tmp113;
  const Scalar _tmp115 = _tmp109 * _tmp28 + _tmp110 * _tmp26;
  const Scalar _tmp116 = _tmp114 * _tmp48 + _tmp115 * _tmp50;
  const Scalar _tmp117 = _tmp115 * _tmp48;
  const Scalar _tmp118 = _tmp114 * _tmp50 - _tmp117;
  const Scalar _tmp119 =
      -Scalar(0.30359999999999998) * _tmp107 - _tmp108 * _tmp52 +
      Scalar(0.040910000000000002) * _tmp112 + Scalar(0.58030000000000004) * _tmp113 -
      _tmp114 * _tmp58 + Scalar(0.023210000000000001) * _tmp116 -
      Scalar(0.58030000000000004) * _tmp117 - Scalar(0.63) * _tmp118 - _tmp23 * _tmp55;
  const Scalar _tmp120 = _tmp17 * _tmp18 - _tmp92;
  const Scalar _tmp121 = _tmp0 * _tmp120 - _tmp19 * _tmp22;
  const Scalar _tmp122 = -_tmp16 * _tmp18 + _tmp89;
  const Scalar _tmp123 = _tmp121 * _tmp28 + _tmp122 * _tmp26;
  const Scalar _tmp124 = _tmp123 * _tmp48;
  const Scalar _tmp125 = _tmp120 * _tmp22;
  const Scalar _tmp126 = -_tmp121 * _tmp26 + _tmp122 * _tmp28;
  const Scalar _tmp127 = -_tmp0 * _tmp19 - _tmp125;
  const Scalar _tmp128 = _tmp126 * _tmp30 - _tmp127 * _tmp32;
  const Scalar _tmp129 = _tmp126 * _tmp32 + _tmp127 * _tmp30;
  const Scalar _tmp130 = -_tmp124 + _tmp129 * _tmp50;
  const Scalar _tmp131 = _tmp123 * _tmp50 + _tmp129 * _tmp48;
  const Scalar _tmp132 = Scalar(0.1801641336) * _tmp104 - Scalar(0.58030000000000004) * _tmp124 -
                         Scalar(0.30359999999999998) * _tmp125 + _tmp126 * _tmp56 -
                         _tmp127 * _tmp52 + Scalar(0.040910000000000002) * _tmp128 -
                         _tmp129 * _tmp58 - Scalar(0.63) * _tmp130 +
                         Scalar(0.023210000000000001) * _tmp131;
  const Scalar _tmp133 = _tmp16 * _tmp28;
  const Scalar _tmp134 = _tmp17 * _tmp26;
  const Scalar _tmp135 = -_tmp0 * _tmp134 - _tmp133;
  const Scalar _tmp136 = _tmp135 * _tmp32;
  const Scalar _tmp137 = _tmp22 * _tmp30;
  const Scalar _tmp138 = _tmp136 - _tmp137 * _tmp17;
  const Scalar _tmp139 = _tmp16 * _tmp26;
  const Scalar _tmp140 = _tmp17 * _tmp28;
  const Scalar _tmp141 = _tmp0 * _tmp140 - _tmp139;
  const Scalar _tmp142 = _tmp138 * _tmp48 + _tmp141 * _tmp50;
  const Scalar _tmp143 = _tmp138 * _tmp50 - _tmp141 * _tmp48;
  const Scalar _tmp144 = _tmp22 * _tmp52;
  const Scalar _tmp145 = _tmp22 * _tmp32;
  const Scalar _tmp146 = _tmp135 * _tmp30 + _tmp145 * _tmp17;
  const Scalar _tmp147 = -_tmp100 * _tmp141 + Scalar(0.58030000000000004) * _tmp136 -
                         _tmp138 * _tmp58 + Scalar(0.023210000000000001) * _tmp142 -
                         Scalar(0.63) * _tmp143 + _tmp144 * _tmp17 +
                         Scalar(0.040910000000000002) * _tmp146 - _tmp17 * _tmp53;
  const Scalar _tmp148 = -_tmp0 * _tmp139 + _tmp140;
  const Scalar _tmp149 = _tmp145 * _tmp16 + _tmp148 * _tmp30;
  const Scalar _tmp150 = _tmp148 * _tmp32;
  const Scalar _tmp151 = -_tmp137 * _tmp16 + _tmp150;
  const Scalar _tmp152 = _tmp0 * _tmp133 + _tmp134;
  const Scalar _tmp153 = _tmp151 * _tmp48 + _tmp152 * _tmp50;
  const Scalar _tmp154 = _tmp151 * _tmp50 - _tmp152 * _tmp48;
  const Scalar _tmp155 =
      -_tmp100 * _tmp152 + _tmp144 * _tmp16 + Scalar(0.040910000000000002) * _tmp149 +
      Scalar(0.58030000000000004) * _tmp150 - _tmp151 * _tmp58 +
      Scalar(0.023210000000000001) * _tmp153 - Scalar(0.63) * _tmp154 - _tmp16 * _tmp53;
  const Scalar _tmp156 = _tmp0 * _tmp32;
  const Scalar _tmp157 = -_tmp137 * _tmp26 - _tmp156;
  const Scalar _tmp158 = _tmp28 * _tmp50;
  const Scalar _tmp159 = _tmp0 * _tmp30;
  const Scalar _tmp160 = -_tmp145 * _tmp26 + _tmp159;
  const Scalar _tmp161 = _tmp158 * _tmp22 + _tmp160 * _tmp48;
  const Scalar _tmp162 = _tmp28 * _tmp48;
  const Scalar _tmp163 = _tmp160 * _tmp50 - _tmp162 * _tmp22;
  const Scalar _tmp164 = -_tmp137 - _tmp156 * _tmp26;
  const Scalar _tmp165 = -_tmp0 * _tmp162 + _tmp164 * _tmp50;
  const Scalar _tmp166 = _tmp26 * _tmp56;
  const Scalar _tmp167 = _tmp100 * _tmp28;
  const Scalar _tmp168 = _tmp145 - _tmp159 * _tmp26;
  const Scalar _tmp169 = _tmp0 * _tmp158 + _tmp164 * _tmp48;
  const Scalar _tmp170 = -_tmp0 * _tmp166 - _tmp0 * _tmp167 + _tmp144 - _tmp164 * _tmp58 -
                         Scalar(0.63) * _tmp165 + Scalar(0.040910000000000002) * _tmp168 +
                         Scalar(0.023210000000000001) * _tmp169 - _tmp53;
  const Scalar _tmp171 = -_tmp0 * _tmp52 + Scalar(0.040910000000000002) * _tmp157 -
                         _tmp160 * _tmp58 + Scalar(0.023210000000000001) * _tmp161 -
                         Scalar(0.63) * _tmp163 - _tmp166 * _tmp22 - _tmp167 * _tmp22 - _tmp55;
  const Scalar _tmp172 = _tmp28 * _tmp30;
  const Scalar _tmp173 = _tmp26 * _tmp50;
  const Scalar _tmp174 = _tmp162 * _tmp32 + _tmp173;
  const Scalar _tmp175 = _tmp26 * _tmp48;
  const Scalar _tmp176 = _tmp158 * _tmp32 - _tmp175;
  const Scalar _tmp177 = -_tmp162 - _tmp173 * _tmp32;
  const Scalar _tmp178 = Scalar(0.040910000000000002) * _tmp30;
  const Scalar _tmp179 = _tmp158 - _tmp175 * _tmp32;
  const Scalar _tmp180 = _tmp166 * _tmp57 - _tmp166 - _tmp167 - Scalar(0.63) * _tmp177 -
                         _tmp178 * _tmp26 + Scalar(0.023210000000000001) * _tmp179;
  const Scalar _tmp181 = _tmp28 * _tmp56;
  const Scalar _tmp182 = -_tmp100 * _tmp26 + Scalar(0.040910000000000002) * _tmp172 +
                         Scalar(0.023210000000000001) * _tmp174 - Scalar(0.63) * _tmp176 -
                         _tmp181 * _tmp57 + _tmp181;
  const Scalar _tmp183 = _tmp30 * _tmp48;
  const Scalar _tmp184 = _tmp30 * _tmp50;
  const Scalar _tmp185 = Scalar(0.58030000000000004) * _tmp30;
  const Scalar _tmp186 = Scalar(0.023210000000000001) * _tmp183 - Scalar(0.63) * _tmp184 -
                         _tmp185 * _tmp57 - Scalar(0.040910000000000002) * _tmp32 - _tmp52;
  const Scalar _tmp187 = Scalar(0.023210000000000001) * _tmp48;
  const Scalar _tmp188 = Scalar(0.63) * _tmp50;
  const Scalar _tmp189 = _tmp178 + _tmp187 * _tmp32 - _tmp188 * _tmp32 - _tmp56 * _tmp57 + _tmp56;
  const Scalar _tmp190 = _tmp186 * _tmp32;
  const Scalar _tmp191 = Scalar(0.58030000000000004) * _tmp50;
  const Scalar _tmp192 =
      Scalar(0.049700000000000001) * _tmp48 + Scalar(0.023210000000000001) * _tmp50;
  const Scalar _tmp193 = _tmp187 - _tmp188 - _tmp58;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 7> _res;

  _res(0, 0) = -Scalar(0.52133399999999996) * _tmp33 * _tmp62 +
               Scalar(0.70710700000000004) * _tmp33 * _tmp88 +
               Scalar(0.52133399999999996) * _tmp59 * _tmp68 -
               Scalar(0.47771400000000003) * _tmp59 * _tmp88 +
               Scalar(0.47771400000000003) * _tmp62 * _tmp81 -
               Scalar(0.70710700000000004) * _tmp68 * _tmp81;
  _res(1, 0) = Scalar(0.52133399999999996) * _tmp51 * _tmp68 -
               Scalar(0.47771400000000003) * _tmp51 * _tmp88 -
               Scalar(0.52133399999999996) * _tmp62 * _tmp65 +
               Scalar(0.47771400000000003) * _tmp62 * _tmp87 +
               Scalar(0.70710700000000004) * _tmp65 * _tmp88 -
               Scalar(0.70710700000000004) * _tmp68 * _tmp87;
  _res(2, 0) = Scalar(0.52133399999999996) * _tmp61 * _tmp68 -
               Scalar(0.47771400000000003) * _tmp61 * _tmp88 -
               Scalar(0.52133399999999996) * _tmp62 * _tmp67 +
               Scalar(0.47771400000000003) * _tmp62 * _tmp86 +
               Scalar(0.70710700000000004) * _tmp67 * _tmp88 -
               Scalar(0.70710700000000004) * _tmp68 * _tmp86;
  _res(3, 0) = Scalar(0.47771400000000003) * _tmp33 + Scalar(0.70710700000000004) * _tmp59 +
               Scalar(0.52133399999999996) * _tmp81;
  _res(4, 0) = Scalar(0.70710700000000004) * _tmp51 + Scalar(0.47771400000000003) * _tmp65 +
               Scalar(0.52133399999999996) * _tmp87;
  _res(5, 0) = Scalar(0.70710700000000004) * _tmp61 + Scalar(0.47771400000000003) * _tmp67 +
               Scalar(0.52133399999999996) * _tmp86;
  _res(0, 1) = Scalar(0.80488899999999997) * _tmp105 * _tmp112 +
               Scalar(0.59342600000000001) * _tmp112 * _tmp132 -
               Scalar(0.59342600000000001) * _tmp119 * _tmp128 -
               Scalar(0.80488899999999997) * _tmp119 * _tmp98;
  _res(1, 1) = -Scalar(0.80488899999999997) * _tmp102 * _tmp119 +
               Scalar(0.80488899999999997) * _tmp105 * _tmp116 +
               Scalar(0.59342600000000001) * _tmp116 * _tmp132 -
               Scalar(0.59342600000000001) * _tmp119 * _tmp131;
  _res(2, 1) = -Scalar(0.80488899999999997) * _tmp103 * _tmp119 +
               Scalar(0.80488899999999997) * _tmp105 * _tmp118 +
               Scalar(0.59342600000000001) * _tmp118 * _tmp132 -
               Scalar(0.59342600000000001) * _tmp119 * _tmp130;
  _res(3, 1) = -Scalar(0.80488899999999997) * _tmp128 + Scalar(0.59342600000000001) * _tmp98;
  _res(4, 1) = Scalar(0.59342600000000001) * _tmp102 - Scalar(0.80488899999999997) * _tmp131;
  _res(5, 1) = Scalar(0.59342600000000001) * _tmp103 - Scalar(0.80488899999999997) * _tmp130;
  _res(0, 2) = -_tmp146 * _tmp155 + _tmp147 * _tmp149;
  _res(1, 2) = -_tmp142 * _tmp155 + _tmp147 * _tmp153;
  _res(2, 2) = -_tmp143 * _tmp155 + _tmp147 * _tmp154;
  _res(3, 2) = -_tmp157;
  _res(4, 2) = -_tmp161;
  _res(5, 2) = -_tmp163;
  _res(0, 3) = _tmp157 * _tmp170 - _tmp168 * _tmp171 - Scalar(0.30359999999999998) * _tmp168;
  _res(1, 3) = _tmp161 * _tmp170 - _tmp169 * _tmp171 - Scalar(0.30359999999999998) * _tmp169;
  _res(2, 3) = _tmp163 * _tmp170 - _tmp165 * _tmp171 - Scalar(0.30359999999999998) * _tmp165;
  _res(3, 3) = _tmp172;
  _res(4, 3) = _tmp174;
  _res(5, 3) = _tmp176;
  _res(0, 4) = _tmp172 * _tmp180 + _tmp182 * _tmp26 * _tmp30;
  _res(1, 4) = _tmp174 * _tmp180 - _tmp179 * _tmp182;
  _res(2, 4) = _tmp176 * _tmp180 - _tmp177 * _tmp182;
  _res(3, 4) = _tmp32;
  _res(4, 4) = -_tmp183;
  _res(5, 4) = -_tmp184;
  _res(0, 5) = _tmp185 + _tmp186 * _tmp30 + _tmp189 * _tmp32;
  _res(1, 5) = -_tmp183 * _tmp189 + _tmp190 * _tmp48 + _tmp48 * _tmp56;
  _res(2, 5) = -_tmp184 * _tmp189 + _tmp190 * _tmp50 + _tmp191 * _tmp32;
  _res(3, 5) = 0;
  _res(4, 5) = _tmp50;
  _res(5, 5) = -_tmp48;
  _res(0, 6) = 0;
  _res(1, 6) = -_tmp191 + _tmp192 * _tmp48 - _tmp193 * _tmp50;
  _res(2, 6) = _tmp100 + _tmp192 * _tmp50 + _tmp193 * _tmp48;
  _res(3, 6) = 1;
  _res(4, 6) = 0;
  _res(5, 6) = 0;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
