// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: adjointMap
 *
 * Args:
 *     joint_angles: Matrix71
 *
 * Outputs:
 *     res: Matrix66
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 6> Leftlowersensoradjointmap(
    const Eigen::Matrix<Scalar, 7, 1>& joint_angles) {
  // Total ops: 195

  // Input arrays

  // Intermediate terms (66)
  const Scalar _tmp0 = std::sin(joint_angles(4, 0));
  const Scalar _tmp1 = std::cos(joint_angles(3, 0));
  const Scalar _tmp2 = std::cos(joint_angles(2, 0));
  const Scalar _tmp3 = 1 - std::cos(joint_angles(0, 0));
  const Scalar _tmp4 = 1 - Scalar(0.499999805352) * _tmp3;
  const Scalar _tmp5 = 1 - std::cos(joint_angles(1, 0));
  const Scalar _tmp6 = Scalar(0.47764205971399998) * _tmp5;
  const Scalar _tmp7 = Scalar(0.36863892073799998) * _tmp3;
  const Scalar _tmp8 = std::sin(joint_angles(0, 0));
  const Scalar _tmp9 = Scalar(0.47771400000000003) * _tmp8;
  const Scalar _tmp10 = _tmp7 - _tmp9;
  const Scalar _tmp11 = 1 - Scalar(0.35215441747600001) * _tmp5;
  const Scalar _tmp12 = Scalar(0.337794913398) * _tmp3;
  const Scalar _tmp13 = Scalar(0.52133399999999996) * _tmp8;
  const Scalar _tmp14 = _tmp12 + _tmp13;
  const Scalar _tmp15 = std::sin(joint_angles(1, 0));
  const Scalar _tmp16 = Scalar(0.59342600000000001) * _tmp15;
  const Scalar _tmp17 = _tmp10 * _tmp11 + _tmp14 * _tmp16 - _tmp4 * _tmp6;
  const Scalar _tmp18 = 1 - Scalar(0.64784630232100004) * _tmp5;
  const Scalar _tmp19 = Scalar(0.80488899999999997) * _tmp15;
  const Scalar _tmp20 = -_tmp10 * _tmp6 + _tmp14 * _tmp19 + _tmp18 * _tmp4;
  const Scalar _tmp21 = std::sin(joint_angles(2, 0));
  const Scalar _tmp22 = _tmp17 * _tmp2 + _tmp20 * _tmp21;
  const Scalar _tmp23 = 1 - Scalar(1.000000719797) * _tmp5;
  const Scalar _tmp24 = -_tmp10 * _tmp16 + _tmp14 * _tmp23 - _tmp19 * _tmp4;
  const Scalar _tmp25 = std::sin(joint_angles(3, 0));
  const Scalar _tmp26 = _tmp1 * _tmp22 + _tmp24 * _tmp25;
  const Scalar _tmp27 = std::cos(joint_angles(4, 0));
  const Scalar _tmp28 = -_tmp17 * _tmp21 + _tmp2 * _tmp20;
  const Scalar _tmp29 = -_tmp0 * _tmp26 + _tmp27 * _tmp28;
  const Scalar _tmp30 = _tmp7 + _tmp9;
  const Scalar _tmp31 = 1 - Scalar(0.728210975245) * _tmp3;
  const Scalar _tmp32 = Scalar(0.249048550476) * _tmp3;
  const Scalar _tmp33 = Scalar(0.70710700000000004) * _tmp8;
  const Scalar _tmp34 = _tmp32 - _tmp33;
  const Scalar _tmp35 = _tmp15 * _tmp34;
  const Scalar _tmp36 = _tmp18 * _tmp30 - _tmp31 * _tmp6 + Scalar(0.80488899999999997) * _tmp35;
  const Scalar _tmp37 = _tmp11 * _tmp31 - _tmp30 * _tmp6 + Scalar(0.59342600000000001) * _tmp35;
  const Scalar _tmp38 = _tmp2 * _tmp36 - _tmp21 * _tmp37;
  const Scalar _tmp39 = _tmp2 * _tmp37 + _tmp21 * _tmp36;
  const Scalar _tmp40 = -_tmp16 * _tmp31 - _tmp19 * _tmp30 + _tmp23 * _tmp34;
  const Scalar _tmp41 = _tmp1 * _tmp39 + _tmp25 * _tmp40;
  const Scalar _tmp42 = -_tmp0 * _tmp41 + _tmp27 * _tmp38;
  const Scalar _tmp43 = _tmp12 - _tmp13;
  const Scalar _tmp44 = 1 - Scalar(0.77178944900500002) * _tmp3;
  const Scalar _tmp45 = _tmp32 + _tmp33;
  const Scalar _tmp46 = _tmp18 * _tmp43 + _tmp19 * _tmp44 - _tmp45 * _tmp6;
  const Scalar _tmp47 = _tmp11 * _tmp45 + _tmp16 * _tmp44 - _tmp43 * _tmp6;
  const Scalar _tmp48 = _tmp2 * _tmp47 + _tmp21 * _tmp46;
  const Scalar _tmp49 = -_tmp16 * _tmp45 - _tmp19 * _tmp43 + _tmp23 * _tmp44;
  const Scalar _tmp50 = _tmp1 * _tmp48 + _tmp25 * _tmp49;
  const Scalar _tmp51 = _tmp2 * _tmp46 - _tmp21 * _tmp47;
  const Scalar _tmp52 = -_tmp0 * _tmp50 + _tmp27 * _tmp51;
  const Scalar _tmp53 = _tmp0 * _tmp28 + _tmp26 * _tmp27;
  const Scalar _tmp54 = _tmp0 * _tmp38 + _tmp27 * _tmp41;
  const Scalar _tmp55 = _tmp0 * _tmp51 + _tmp27 * _tmp50;
  const Scalar _tmp56 = _tmp22 * _tmp25;
  const Scalar _tmp57 = _tmp1 * _tmp24 - _tmp56;
  const Scalar _tmp58 = _tmp25 * _tmp39;
  const Scalar _tmp59 = _tmp1 * _tmp40 - _tmp58;
  const Scalar _tmp60 = _tmp25 * _tmp48;
  const Scalar _tmp61 = _tmp1 * _tmp49 - _tmp60;
  const Scalar _tmp62 = Scalar(0.30359999999999998) - Scalar(0.30359999999999998) * _tmp1;
  const Scalar _tmp63 = -_tmp40 * _tmp62 + Scalar(0.0053400000000000001) * _tmp42 -
                        Scalar(0.029790000000000001) * _tmp54 -
                        Scalar(0.30359999999999998) * _tmp58 - Scalar(0.51190000000000002) * _tmp59;
  const Scalar _tmp64 = -_tmp49 * _tmp62 + Scalar(0.0053400000000000001) * _tmp52 -
                        Scalar(0.029790000000000001) * _tmp55 -
                        Scalar(0.30359999999999998) * _tmp60 - Scalar(0.51190000000000002) * _tmp61;
  const Scalar _tmp65 = -_tmp24 * _tmp62 + Scalar(0.0053400000000000001) * _tmp29 -
                        Scalar(0.029790000000000001) * _tmp53 -
                        Scalar(0.30359999999999998) * _tmp56 - Scalar(0.51190000000000002) * _tmp57;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 6> _res;

  _res(0, 0) = _tmp29;
  _res(1, 0) = _tmp42;
  _res(2, 0) = _tmp52;
  _res(3, 0) = 0;
  _res(4, 0) = 0;
  _res(5, 0) = 0;
  _res(0, 1) = _tmp53;
  _res(1, 1) = _tmp54;
  _res(2, 1) = _tmp55;
  _res(3, 1) = 0;
  _res(4, 1) = 0;
  _res(5, 1) = 0;
  _res(0, 2) = _tmp57;
  _res(1, 2) = _tmp59;
  _res(2, 2) = _tmp61;
  _res(3, 2) = 0;
  _res(4, 2) = 0;
  _res(5, 2) = 0;
  _res(0, 3) = -_tmp42 * _tmp64 + _tmp52 * _tmp63;
  _res(1, 3) = _tmp29 * _tmp64 - _tmp52 * _tmp65;
  _res(2, 3) = -_tmp29 * _tmp63 + _tmp42 * _tmp65;
  _res(3, 3) = _tmp29;
  _res(4, 3) = _tmp42;
  _res(5, 3) = _tmp52;
  _res(0, 4) = -_tmp54 * _tmp64 + _tmp55 * _tmp63;
  _res(1, 4) = _tmp53 * _tmp64 - _tmp55 * _tmp65;
  _res(2, 4) = -_tmp53 * _tmp63 + _tmp54 * _tmp65;
  _res(3, 4) = _tmp53;
  _res(4, 4) = _tmp54;
  _res(5, 4) = _tmp55;
  _res(0, 5) = -_tmp59 * _tmp64 + _tmp61 * _tmp63;
  _res(1, 5) = _tmp57 * _tmp64 - _tmp61 * _tmp65;
  _res(2, 5) = -_tmp57 * _tmp63 + _tmp59 * _tmp65;
  _res(3, 5) = _tmp57;
  _res(4, 5) = _tmp59;
  _res(5, 5) = _tmp61;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
