// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: adjointInvMap
 *
 * Args:
 *     joint_angles: Matrix71
 *
 * Outputs:
 *     res: Matrix66
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 6> Leftlowersensoradjointinvmap(
    const Eigen::Matrix<Scalar, 7, 1>& joint_angles) {
  // Total ops: 195

  // Input arrays

  // Intermediate terms (66)
  const Scalar _tmp0 = std::sin(joint_angles(4, 0));
  const Scalar _tmp1 = std::cos(joint_angles(3, 0));
  const Scalar _tmp2 = std::cos(joint_angles(2, 0));
  const Scalar _tmp3 = 1 - std::cos(joint_angles(0, 0));
  const Scalar _tmp4 = 1 - Scalar(0.499999805352) * _tmp3;
  const Scalar _tmp5 = 1 - std::cos(joint_angles(1, 0));
  const Scalar _tmp6 = Scalar(0.47764205971399998) * _tmp5;
  const Scalar _tmp7 = Scalar(0.36863892073799998) * _tmp3;
  const Scalar _tmp8 = std::sin(joint_angles(0, 0));
  const Scalar _tmp9 = Scalar(0.47771400000000003) * _tmp8;
  const Scalar _tmp10 = _tmp7 - _tmp9;
  const Scalar _tmp11 = 1 - Scalar(0.35215441747600001) * _tmp5;
  const Scalar _tmp12 = Scalar(0.337794913398) * _tmp3;
  const Scalar _tmp13 = Scalar(0.52133399999999996) * _tmp8;
  const Scalar _tmp14 = _tmp12 + _tmp13;
  const Scalar _tmp15 = std::sin(joint_angles(1, 0));
  const Scalar _tmp16 = Scalar(0.59342600000000001) * _tmp15;
  const Scalar _tmp17 = _tmp10 * _tmp11 + _tmp14 * _tmp16 - _tmp4 * _tmp6;
  const Scalar _tmp18 = 1 - Scalar(0.64784630232100004) * _tmp5;
  const Scalar _tmp19 = Scalar(0.80488899999999997) * _tmp15;
  const Scalar _tmp20 = -_tmp10 * _tmp6 + _tmp14 * _tmp19 + _tmp18 * _tmp4;
  const Scalar _tmp21 = std::sin(joint_angles(2, 0));
  const Scalar _tmp22 = _tmp17 * _tmp2 + _tmp20 * _tmp21;
  const Scalar _tmp23 = 1 - Scalar(1.000000719797) * _tmp5;
  const Scalar _tmp24 = -_tmp10 * _tmp16 + _tmp14 * _tmp23 - _tmp19 * _tmp4;
  const Scalar _tmp25 = std::sin(joint_angles(3, 0));
  const Scalar _tmp26 = _tmp1 * _tmp22 + _tmp24 * _tmp25;
  const Scalar _tmp27 = std::cos(joint_angles(4, 0));
  const Scalar _tmp28 = -_tmp17 * _tmp21 + _tmp2 * _tmp20;
  const Scalar _tmp29 = -_tmp0 * _tmp26 + _tmp27 * _tmp28;
  const Scalar _tmp30 = _tmp0 * _tmp28 + _tmp26 * _tmp27;
  const Scalar _tmp31 = _tmp22 * _tmp25;
  const Scalar _tmp32 = _tmp1 * _tmp24 - _tmp31;
  const Scalar _tmp33 = _tmp7 + _tmp9;
  const Scalar _tmp34 = 1 - Scalar(0.728210975245) * _tmp3;
  const Scalar _tmp35 = Scalar(0.249048550476) * _tmp3;
  const Scalar _tmp36 = Scalar(0.70710700000000004) * _tmp8;
  const Scalar _tmp37 = _tmp35 - _tmp36;
  const Scalar _tmp38 = _tmp15 * _tmp37;
  const Scalar _tmp39 = _tmp18 * _tmp33 - _tmp34 * _tmp6 + Scalar(0.80488899999999997) * _tmp38;
  const Scalar _tmp40 = _tmp11 * _tmp34 - _tmp33 * _tmp6 + Scalar(0.59342600000000001) * _tmp38;
  const Scalar _tmp41 = _tmp2 * _tmp39 - _tmp21 * _tmp40;
  const Scalar _tmp42 = _tmp2 * _tmp40 + _tmp21 * _tmp39;
  const Scalar _tmp43 = -_tmp16 * _tmp34 - _tmp19 * _tmp33 + _tmp23 * _tmp37;
  const Scalar _tmp44 = _tmp1 * _tmp42 + _tmp25 * _tmp43;
  const Scalar _tmp45 = -_tmp0 * _tmp44 + _tmp27 * _tmp41;
  const Scalar _tmp46 = _tmp0 * _tmp41 + _tmp27 * _tmp44;
  const Scalar _tmp47 = _tmp25 * _tmp42;
  const Scalar _tmp48 = _tmp1 * _tmp43 - _tmp47;
  const Scalar _tmp49 = _tmp12 - _tmp13;
  const Scalar _tmp50 = 1 - Scalar(0.77178944900500002) * _tmp3;
  const Scalar _tmp51 = _tmp35 + _tmp36;
  const Scalar _tmp52 = _tmp18 * _tmp49 + _tmp19 * _tmp50 - _tmp51 * _tmp6;
  const Scalar _tmp53 = _tmp11 * _tmp51 + _tmp16 * _tmp50 - _tmp49 * _tmp6;
  const Scalar _tmp54 = _tmp2 * _tmp53 + _tmp21 * _tmp52;
  const Scalar _tmp55 = -_tmp16 * _tmp51 - _tmp19 * _tmp49 + _tmp23 * _tmp50;
  const Scalar _tmp56 = _tmp1 * _tmp54 + _tmp25 * _tmp55;
  const Scalar _tmp57 = _tmp2 * _tmp52 - _tmp21 * _tmp53;
  const Scalar _tmp58 = -_tmp0 * _tmp56 + _tmp27 * _tmp57;
  const Scalar _tmp59 = _tmp0 * _tmp57 + _tmp27 * _tmp56;
  const Scalar _tmp60 = _tmp25 * _tmp54;
  const Scalar _tmp61 = _tmp1 * _tmp55 - _tmp60;
  const Scalar _tmp62 = Scalar(0.30359999999999998) - Scalar(0.30359999999999998) * _tmp1;
  const Scalar _tmp63 = -_tmp43 * _tmp62 + Scalar(0.0053400000000000001) * _tmp45 -
                        Scalar(0.029790000000000001) * _tmp46 -
                        Scalar(0.30359999999999998) * _tmp47 - Scalar(0.51190000000000002) * _tmp48;
  const Scalar _tmp64 = -_tmp55 * _tmp62 + Scalar(0.0053400000000000001) * _tmp58 -
                        Scalar(0.029790000000000001) * _tmp59 -
                        Scalar(0.30359999999999998) * _tmp60 - Scalar(0.51190000000000002) * _tmp61;
  const Scalar _tmp65 = -_tmp24 * _tmp62 + Scalar(0.0053400000000000001) * _tmp29 -
                        Scalar(0.029790000000000001) * _tmp30 -
                        Scalar(0.30359999999999998) * _tmp31 - Scalar(0.51190000000000002) * _tmp32;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 6> _res;

  _res(0, 0) = _tmp29;
  _res(1, 0) = _tmp30;
  _res(2, 0) = _tmp32;
  _res(3, 0) = 0;
  _res(4, 0) = 0;
  _res(5, 0) = 0;
  _res(0, 1) = _tmp45;
  _res(1, 1) = _tmp46;
  _res(2, 1) = _tmp48;
  _res(3, 1) = 0;
  _res(4, 1) = 0;
  _res(5, 1) = 0;
  _res(0, 2) = _tmp58;
  _res(1, 2) = _tmp59;
  _res(2, 2) = _tmp61;
  _res(3, 2) = 0;
  _res(4, 2) = 0;
  _res(5, 2) = 0;
  _res(0, 3) = -_tmp45 * _tmp64 + _tmp58 * _tmp63;
  _res(1, 3) = -_tmp46 * _tmp64 + _tmp59 * _tmp63;
  _res(2, 3) = -_tmp48 * _tmp64 + _tmp61 * _tmp63;
  _res(3, 3) = _tmp29;
  _res(4, 3) = _tmp30;
  _res(5, 3) = _tmp32;
  _res(0, 4) = _tmp29 * _tmp64 - _tmp58 * _tmp65;
  _res(1, 4) = _tmp30 * _tmp64 - _tmp59 * _tmp65;
  _res(2, 4) = _tmp32 * _tmp64 - _tmp61 * _tmp65;
  _res(3, 4) = _tmp45;
  _res(4, 4) = _tmp46;
  _res(5, 4) = _tmp48;
  _res(0, 5) = -_tmp29 * _tmp63 + _tmp45 * _tmp65;
  _res(1, 5) = -_tmp30 * _tmp63 + _tmp46 * _tmp65;
  _res(2, 5) = -_tmp32 * _tmp63 + _tmp48 * _tmp65;
  _res(3, 5) = _tmp58;
  _res(4, 5) = _tmp59;
  _res(5, 5) = _tmp61;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
